# Generated by Django 5.1.5 on 2025-01-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
