# Generated by Django 5.1.6 on 2025-02-22 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerapp', '0003_visitorcounter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitorCounter',
        ),
    ]
