# Generated by Django 5.1.5 on 2025-02-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuelist',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
