# Generated by Django 5.1.5 on 2025-01-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuelist',
            name='image',
            field=models.FileField(upload_to='venueimages/'),
        ),
    ]
