# Generated by Django 5.1.5 on 2025-02-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_venuelist_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_Category_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='categoryimages/')),
            ],
        ),
    ]
