# Generated by Django 5.1.5 on 2025-02-17 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_game_category_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuelist',
            name='contact',
        ),
        migrations.AddField(
            model_name='venuelist',
            name='games',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.game_category_list'),
        ),
    ]
