# Generated by Django 5.1.6 on 2025-02-18 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_remove_venuelist_contact_venuelist_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuelist',
            name='games',
        ),
        migrations.CreateModel(
            name='VenueGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.game_category_list')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.venuelist')),
            ],
        ),
    ]
