# Generated by Django 5.1.6 on 2025-02-24 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_visitorcounter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorcounter',
            name='count',
        ),
        migrations.AddField(
            model_name='visitorcounter',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitorcounter',
            name='visited_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
