# Generated by Django 5.1.6 on 2025-02-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_remove_visitorcounter_count_visitorcounter_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_description', models.TextField()),
                ('venue_amenities', models.JSONField(default=list)),
                ('venue_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
