# Generated by Django 5.1.6 on 2025-02-25 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_venue_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_description', models.TextField()),
                ('venue_amenities', models.JSONField(default=list)),
                ('venue_time', models.TimeField(blank=True, null=True)),
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='adminapp.venuelist')),
            ],
        ),
        migrations.DeleteModel(
            name='Venue_details',
        ),
    ]
