# Generated by Django 5.1.6 on 2025-03-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_venuedetails_delete_venue_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuelist',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venuelist',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
