# Generated by Django 5.1.6 on 2025-03-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_venuelist_latitude_venuelist_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='venuedetails',
            old_name='venue_time',
            new_name='closing_time',
        ),
        migrations.AddField(
            model_name='venuedetails',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='venuedetails',
            name='venue_amenities',
        ),
        migrations.AddField(
            model_name='venuedetails',
            name='venue_amenities',
            field=models.ManyToManyField(blank=True, to='adminapp.amenity'),
        ),
    ]
