# Generated by Django 5.1.6 on 2025-03-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_amenity_rename_venue_time_venuedetails_closing_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuedetails',
            name='venue_amenities',
        ),
        migrations.DeleteModel(
            name='Amenity',
        ),
        migrations.AddField(
            model_name='venuedetails',
            name='venue_amenities',
            field=models.JSONField(default=list),
        ),
    ]
