# Generated by Django 5.1.6 on 2025-03-11 06:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_hostedgame'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedgame',
            name='players',
            field=models.ManyToManyField(related_name='joined_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
