# Generated by Django 5.1.6 on 2025-03-18 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0019_remove_booking_court_delete_court'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='VenueGamePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('game_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.game_category_list')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.venuelist')),
            ],
        ),
    ]
