# Generated by Django 5.1.6 on 2025-03-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0020_booking_total_price_venuegameprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuegameprice',
            name='time_slot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
