# Generated by Django 5.1.6 on 2025-03-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0021_venuegameprice_time_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuegameprice',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='venuegames',
            name='time_slot',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
